// Current MCOC playable champion roster (updated September 11, 2026).
// Any name here that's missing from the database is added on startup, unless an
// officer removed it from the Admin page (see REMOVED_CHAMPIONS in db.ts).
// Temporary/event-only champions that are no longer playable are intentionally excluded.
export const SEED_CHAMPIONS: string[] = [
  "Abomination", "Abomination (Immortal)", "Absorbing Man", "Adam Warlock", "Agatha Harkness",
  "Agent Venom", "Air-Walker", "America Chavez", "Angela", "Annihilus",
  "Ant-Man", "Ant-Man (Future)", "Anti-Venom", "Apocalypse", "Arcade",
  "Archangel", "Arnim Zola", "Attuma", "Baron Zemo", "Bastion",
  "Beast", "Beta Ray Bill", "Bishop", "Black Bolt", "Black Cat",
  "Black Panther", "Black Panther (Civil War)", "Black Tarantula", "Black Widow", "Black Widow (Claire Voyant)",
  "Black Widow (Deadly Origin)", "Blade", "Blade (Stellar-Forged)", "Blue Marvel", "Bullseye",
  "Cable", "Captain America", "Captain America (Infinity War)", "Captain America (Sam Wilson)", "Captain America (WWII)",
  "Captain Britain", "Captain Marvel", "Captain Marvel (Classic)", "Carnage", "Cassandra Nova",
  "Cassie Lang", "Chee'ilth", "Civil Warrior", "Colossus", "Corvus Glaive",
  "Cosmic Ghost Rider", "Count Nefaria", "Crossbones", "Cull Obsidian", "Cyclops (Blue Team)",
  "Cyclops (New Xavier School)", "Dani Moonstar", "Daredevil (Classic)", "Daredevil (Hell's Kitchen)", "Dark Phoenix",
  "Darkhawk", "Dazzler", "Deadpool", "Deadpool (X-Force)", "Diablo",
  "Doctor Bong", "Doctor Doom", "Doctor Octopus", "Doctor Strange", "Doctor Voodoo",
  "Domino", "Dormammu", "Dracula", "Dragon Man", "Drax",
  "Dust", "Ebony Maw", "Electro", "Elektra", "Elsa Bloodstone",
  "Emma Frost", "Enchantress", "Falcon", "Falcon (Joaquín Torres)", "Franken-Castle",
  "Galan", "Gambit", "Gamora", "Gentle", "Ghost",
  "Ghost Rider", "Gladiator", "Goldpool", "Gorr", "Green Goblin",
  "Green Goblin (Stellar-Forged)", "Groot", "Guardian", "Guillotine", "Guillotine (Deathless)",
  "Guillotine 2099", "Gwenom", "Gwenpool", "Havok", "Hawkeye",
  "Heimdall", "Hela", "Hercules", "High Evolutionary", "Hit-Monkey",
  "Hobgoblin (Phil Urich)", "Howard the Duck", "Hulk", "Hulk (Immortal)", "Hulk (Ragnarok)",
  "Hulkbuster", "Hulkling", "Human Torch", "Hyperion", "Iceman",
  "Ikaris", "Imperiosa", "Invisible Woman", "Iron Fist", "Iron Fist (Immortal)",
  "Iron Man", "Iron Man (Infamous)", "Iron Man (Infinity War)", "Iron Patriot", "Ironheart",
  "Isophyne", "Jabari Panther", "Jack O'Lantern", "Jean Grey", "Jessica Jones",
  "Joe Fixit", "Jubilee", "Juggernaut", "Kang the Conqueror", "Karnak",
  "Karolina Dean", "Kate Bishop", "Killmonger", "Kindred", "King Groot",
  "King Groot (Deathless)", "Kingpin", "Kitty Pryde", "Knull", "Korg",
  "Kraven", "Kushala", "Lady Deathstrike", "Lizard", "Loki",
  "Longshot", "Luke Cage", "Lumatrix", "M'Baku", "M.O.D.O.K.",
  "Madelyne Pryor", "Maestro", "Magik", "Magneto", "Magneto (House of X)",
  "Man-Thing", "Mangog", "Mantis", "Masacre", "Medusa",
  "Mephisto", "Mister Fantastic", "Mister Negative", "Mister Sinister", "Misty Knight",
  "Mojo", "Mole Man", "Moon Knight", "Moondragon", "Morbius",
  "Mordo", "Morningstar", "Mr. Knight", "Ms. Marvel", "Ms. Marvel (Kamala Khan)",
  "Mysterio", "Namor", "Nebula", "Negasonic Teenage Warhead", "Nick Fury",
  "Nico Minoru", "Night Thrasher", "Nightcrawler", "Nimrod", "Northstar",
  "Nova", "Odin", "Okoye", "Old Man Logan", "Omega Red",
  "Omega Sentinel", "Onslaught", "Patriot", "Peni Parker", "Phoenix",
  "Photon", "Phyla-Vell", "Pixie", "Platinumpool", "Professor X",
  "Prowler", "Proxima Midnight", "Psycho-Man", "Psylocke", "Punisher",
  "Punisher 2099", "Purgatory", "Quake", "Quicksilver", "Red Goblin",
  "Red Guardian", "Red Hulk", "Red Skull", "Rhino", "Rintrah",
  "Rocket Raccoon", "Rogue", "Ronan", "Ronin", "Ruby Thursday",
  "Sabretooth", "Sandman", "Sasquatch", "Sauron", "Scarlet Witch",
  "Scarlet Witch (Classic)", "Scorpion", "Scream", "Sentinel", "Sentry",
  "Sersi", "Shang-Chi", "Shathra", "Shatterstar", "She-Hulk",
  "She-Hulk (Deathless)", "Shocker", "Shuri", "Silk", "Silver Centurion",
  "Silver Sable", "Silver Samurai", "Silver Surfer", "Solvarch", "Sorcerer Supreme",
  "Spider-Gwen", "Spider-Ham", "Spider-Man (Classic)", "Spider-Man (Miles Morales)", "Spider-Man (Pavitr Prabhakar)",
  "Spider-Man (Stark Enhanced)", "Spider-Man (Stealth Suit)", "Spider-Man (Supreme)", "Spider-Man (Symbiote)", "Spider-Man 2099",
  "Spider-Man Noir", "Spider-Punk", "Spider-Slayer (J. Jonah Jameson)", "Spider-Woman (Jessica Drew)", "Spiral",
  "Spot", "Squirrel Girl", "Star-Lord", "Star-Lord (Stellar-Forged)", "Storm",
  "Storm (Pyramid X)", "Stryfe", "Sunspot", "Super-Skrull", "Superior Iron Man",
  "Symbiote Supreme", "Taskmaster", "Terrax", "Thanos", "Thanos (Deathless)",
  "The Champion", "The Destroyer", "The Hood", "The Leader", "The Maker",
  "The Overseer", "The Serpent", "Thing", "Thor", "Thor (Jane Foster)",
  "Thor (Ragnarok)", "Tigra", "Titania", "Toad", "Ultron",
  "Ultron (Classic)", "Unstoppable Colossus", "Valkyrie", "Venom", "Venom the Duck",
  "Venompool", "Vision", "Vision (Aarkus)", "Vision (Age of Ultron)", "Vision (Deathless)",
  "Viv Vision", "Void", "Vox", "Vulture", "War Machine",
  "Warlock", "Wasp", "Wave", "Werewolf By Night", "White Tiger",
  "Wiccan", "Winter Soldier", "Wolverine", "Wolverine (Weapon X)", "Wolverine (X-23)",
  "Wong", "Yelena Belova", "Yellowjacket", "Yondu", "Ægon"
];
